SELECT * FROM CLIENTE_W3
SELECT NOME,ENDERECO,COD_CLIENTE FROM CLIENTE_W3
WHERE COD_CLIENTE>40

SELECT * FROM CLIENTE_W3
WHERE PAIS='Germany'

	SELECT nome,endereco,cidade FROM CLIENTE_W3
	WHERE PAIS='brazil'

	SELECT * FROM CLIENTE_W3
	WHERE PAIS LIKE'B%'

SELECT PAIS, COUNT(*) FROM CLIENTE_W3 GROUP BY PAIS

SELECT UPPER (NOME)FROM CLIENTE_W3

SELECT MAX (COD_CLIENTE)FROM CLIENTE_W3

SELECT MIN (COD_CLIENTE)FROM CLIENTE_W3

SELECT MIN (COD_CLIENTE)FROM CLIENTE_W3

SELECT AVG(COD_CLIENTE) FROM CLIENTE_W3--MEDIA

SELECT POWER (2,5) --POTENCIA
SELECT POWER (3,4)

SELECT PI()-- PI

SELECT GETDATE()--DA A DATA ATUAL


