SELECT * FROM CADFUN

SELECT NOME,FUNCAO,YEAR(ADMISSAO)AS ANO FROM CADFUN;
SELECT NOME,FUNCAO,DATENAME(MM,ADMISSAO) FROM CADFUN

SELECT NOME,FUNCAO,DATENAME(MONTH,ADMISSAO) AS MÊS FROM CADFUN
SELECT NOME,FUNCAO,DATENAME(DW,ADMISSAO) AS DIA FROM CADFUN

SELECT NOME,FUNCAO,DATENAME(DY,ADMISSAO) AS DIA FROM CADFUN

SELECT DATEPART(DY,GETDATE())

SELECT DATEPART(DY,GETDATE())*5


?