

SELECT 
	cliente.ESTADO,
	SUM(VENDA.VALOR) AS TOTAL
	FROM cliente JOIN VENDA ON(cliente.CODCLI= venda.CODCLI)
	GROUP BY cliente.ESTADO


SELECT 
	cliente.CIDADE,
	SUM(VENDA.VALOR) AS TOTAL,
	AVG(VENDA.VALOR) AS MEDIA,
	COUNT(CLIENTE.CODCLI) AS QUANTIDADE 
	FROM cliente JOIN VENDA ON(cliente.CODCLI= venda.CODCLI)
	GROUP BY cliente.CIDADE
	ORDER BY TOTAL
