USE VIRTUAL_FINAL

--USE master;

SELECT * FROM CADFUN;
--Selecionando somente determinadas colunas
--Exemplo: nome e salário
SELECT NOME,SALARIO FROM CADFUN;

SELECT NOME,SALARIO,FILHOS FROM CADFUN;

--Selecionando dados com filtro  com filtro para 
--Trazer alguns registros 

SELECT * FROM CADFUN
WHERE DEPTO=3 OR DEPTO=2;

SELECT NOME,CIDADE,ESTADO FROM CLIENTE
WHERE ESTADO='SP';

SELECT NOME,SALARIO FROM CADFUN
WHERE SALARIO>1500;

SELECT * FROM CADFUN
WHERE FUNCAO='VENDEDOR' OR FUNCAO='VENDEDORA';

SELECT * FROM CADFUN;

SELECT CODFUN,NOME,FUNCAO FROM CADFUN
WHERE CODFUN>10;