use VIRTUAL_FINAL

SELECT * FROM CADFUN;

SELECT NOME, SALARIO FROM CADFUN;

SELECT NOME, SALARIO , FILHOS FROM CADFUN;

--//SELECT FROM DAR

SELECT * FROM CADFUN
WHERE DEPTO = 3 OR DEPTO = 2;

SELECT * FROM venda;

SELECT * FROM cliente
WHERE ESTADO = 'SP';

SELECT * FROM cliente
WHERE ESTADO = 'RJ';

SELECT * FROM cliente
WHERE ESTADO = 'MG';

SELECT NOME, CIDADE, ESTADO
FROM cliente
WHERE ESTADO = 'SP';

SELECT NOME, SALARIO
FROM CADFUN
WHERE SALARIO > 1500;

SELECT * FROM CADFUN
WHERE FUNCAO='VENDEDOR' OR FUNCAO='VENDEDORA';

SELECT CODFUN, NOME, FUNCAO
FROM CADFUN
WHERE CODFUN > 10;
